### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by stuffmatic** [AlexCharlton/midi-msg#2]
This crate could be really useful in `no_std` environments like microcontrollers. There don't seem to be any dependencies on `std` that can't be replaced with `alloc` counterparts. I'm happy to submit a PR adding `no_std` support if you're interested.

**Comment by AlexCharlton** [comment]
Good idea! Happy to have the contribution :)

**Comment by stuffmatic** [comment]
I just got the crate to compile with `no_std` support, but it turned out to be a bit more work than I anticipated. Here are my findings so far:

* The `ascii` crate provides `AsciiString` in `no_std` environments if the `alloc` feature is enabled. However, this feature [seems to have been added](https://github.com/tomprogrammer/rust-ascii/commit/1a910338f4549cf631f163f161559da0d0ad7d11) after [the 1.0 release](https://github.com/tomprogrammer/rust-ascii/releases/tag/v1.0.0), which means the `ascii` crate must be fetched from the git repo.
* There are some math functions that are only available in `std`. I used the [`micromath`](https://docs.rs/micromath/1.1.1/micromath/) crate, which provides `no_std` compatible drop in replacements for `f32` math functions. Some of these, like `powf` and `log2`, are only approximations though, so it would be necessary to verify that the accuracy is good enough.

The above issues seem to (only?) pertain to "exotic" features like sysex, so it might be an option to add cargo feature flags for disabling certain features for `no_std` builds. This would also provide a way of reducing the binary size, which is useful in resource constrained environments. 

I still think it would be really nice if this crate had `no_std` support, even if it means (at least initially) sacrificing/disabling some  features, and I'm happy to work on this if we can find a way forward. It would be interesting to hear your thoughts about this.

**Comment by AlexCharlton** [comment]
Nice findings!

Regarding `ascii`: I'm not particularly against using a git revision. Perhaps the author of that crate could be convinced to cut a new version, though.

Regarding `micromath`: I'm not at all opposed. The precision of the math operations performed for this crate is inherently limited by the low bit depth of the numbers they're operating on, so I don't foresee any problems.

So that said, it sounds like we can get to `no_std` without hiding functionality behind features. I can see the utility in having a reduced binary size too, but I think we can agree that this would best be an additional feature rather than a way of attaining `no_std`. Certainly the majority of this crate lives under `SystemExclusiveMsg` so that would be a natural cut-point for sure. So yeah, I'd also be open to a `no_sysex` feature.

**Comment by AlexCharlton** [comment]
Added by #3. 👏 @stuffmatic 

Will create a 0.4 release when #4 is merged.
