### ISSUE TITLE
Bug: Crash on midi file parse

### ISSUE THREAD

**Issue by sevonj** [AlexCharlton/midi-msg#26]
Trying to parse this file causes a panic.

[midimsg-sample-crash.zip](https://github.com/user-attachments/files/18150259/midimsg-sample-crash.zip)

```
thread 'main' panicked at /home/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/midi-msg-0.7.4/src/file.rs:661:58:
index out of bounds: the len is 0 but the index is 0
```

I wouldn't be surprised if there's something wrong with this one, as this was the only midi file to do this, out of many that I tested.

**Comment by AlexCharlton** [comment]
As you suspected, this file _does_ include an invalid event. In particular it contains a `SequenceNumber` meta event that has a stated length of `0`. Because `SequenceNumber` expects a number, there's no real way for us to proceed from this. Are the following bytes actually the sequence number or is the length value correct and we should skip onto the next event and abort parsing the meta event? There's no way to know.

That said, I added an actual error to capture this, rather than a panic, which is of course not what we want :) 

https://github.com/AlexCharlton/midi-msg/commit/8499a6c5d50029737eb1bf5859e4986945703bf8
